// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: ServerProtocols.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
using System.Collections.Generic;

using System.ComponentModel;
using Engine;
using Engine.IService;

namespace Engine.IService
{

    public enum ServerState
    {
        Off = 0,
        Idle = 1,
        Avail = 2,
        Busy = 3,
        Full = 4,
    }

    public enum ApplicationTypeEnum: byte
    {
        None = 0,
        NodeEureka,
        GlobalEureka,
        Logic,
        Login,
        World,
    }

    public struct ApplicationInfo
    {
        public ApplicationTypeEnum ApplicationType { get; set; }
        public byte AppID { get; set; }
    }

    public class ServiceTypeWrapper
    {
        public ApplicationTypeEnum ServiceType { get; set; }
    }

    public class NodeInfo
    {
        public ushort NodeId { get; set; } //0 表示还没分配

        public string ServerIP { get; set; } //TODO 看看类型换成IPEndPoint好不好使
        public int ServerPort { get; set; }

        public List<ApplicationInfo> ApplicationInfoList { get; set; } = new List<ApplicationInfo>();


        public List<ApplicationInfo> GetServiceByType(ApplicationTypeEnum serviceTypeEnum)
        {
            var retList = new List<ApplicationInfo>();
            foreach (var serviceInfo in ApplicationInfoList)
            {
                if (serviceInfo.ApplicationType.Equals(serviceTypeEnum))
                    retList.Add(serviceInfo);
            }
            return retList;
        }
    }

    public class NodePubRet
    {
        public ushort NodeId { get; set; }
        public List<NodeInfo> NodeInfoList { get; set; } = new List<NodeInfo>();
    }



}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
